[template.enviroment]
    RALLY_API_URL = "https://api.rally.io/v1"
    RALLY_USERNAME = "username/email used during app registration"
    RALLY_PASSWORD = "password for application account"
    CALLBACK_URL = "functions_uri/user"